spring:
  application:
    name: gateway-service
  cloud:
    nacos:
        discovery:
          server-addr: 192.168.116.128:8848,192.168.116.129:8848,192.168.116.130:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: data-service2  
          uri: lb://brillianceconsumer/
          filters:
             - StripPrefix=1
          predicates:
            - Path=/member/**
    inetutils:
     preferred-networks:
      - 192.168.116.1


    
        
         



    
        
         

